[package]
name = "brakefri-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
p3-field.workspace = true
p3-goldilocks.workspace = true
p3-dft.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
p3-symmetric.workspace = true
p3-keccak.workspace = true
p3-sha256.workspace = true
p3-blake3.workspace = true
p3-challenger.workspace = true
p3-commit.workspace = true
p3-merkle-tree.workspace = true
p3-util.workspace = true
p3-f128-adapter.workspace = true
brakefri-runtime.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
num-bigint.workspace = true
